### PR TITLE
feature-site-status checking sever status

### PR DESCRIPTION
**Pull request by rcoffie**
Sever Status feature

### CODE REVIEW

**Comment by gray-adeyi** [comment]
Hello rcoffie...nice enhancements...it would we awesome if you can make a little modifications to you PR before i merge it. `server_status` and `status` pretty much do the same thing, so you can scrap any of the fields that seems fit.

**Comment by gray-adeyi** [comment]
Also please try to type hint you code if possible. I'll still merge your changes regardless.
```python
from enum import IntEnum
class ServerStatus(IntEnum):
    online = 0
    offline = 1

 @property
    def server_status(self) -> ServerStatus:
        url = self.url
        try:
            response = requests.get(url)
            if response.status_code == 200:
                return ServerStatus.online
        except requests.exceptions.ConnectionError as e:
            return ServerStatus.offline
```

**Review by gray-adeyi — CHANGES_REQUESTED** [review]
Hello rcoffie...nice enhancements...it would we awesome if you can make a little modifications to you PR before i merge it. `server_status` and `status` pretty much do the same thing, so you can scrap any of the fields that seems fit.

Also please try to type hint you code if possible. I'll still merge your changes regardless.
```python
from enum import IntEnum
class ServerStatus(IntEnum):
    online = 0
    offline = 1

 @property
    def server_status(self) -> ServerStatus:
        url = self.url
        try:
            response = requests.get(url)
            if response.status_code == 200:
                return ServerStatus.online
        except requests.exceptions.ConnectionError as e:
            return ServerStatus.offline
```

**Comment by rcoffie** [comment]
oki , thanks for the review

**Comment by gray-adeyi** [comment]
I'll be awaiting your changes

**Review by gray-adeyi — APPROVED** [review]
Nice work

**Pull request merged**
